def classFactory(iface):
    from .plugin_mh_sm import MhSmPlugin
    return MhSmPlugin(iface)
# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MhSmPlugin
                                 A QGIS plugin
 Projection MH ↔ SM (MED)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-08
        copyright            : (C) 2026 by Bastien Doré
        email                : bastien.dorepr0@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MhSmPlugin class from file MhSmPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plugin_mh_sm import MhSmPlugin
    return MhSmPlugin(iface)
